# Generated by Django 3.0.10 on 2020-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
