# Generated by Django 3.0.10 on 2020-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_registeruser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='is_admin',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
